version: 2

formats:
  - pdf
  - epub

sphinx:
  configuration: docs/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

python:
  version: 3.10
  install:
    - method: pip
    - requirements: docs/requirements.txt
      