[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "duellingdynasty"
authors = [{name = "Tade Strehk", email = "tade99@gmx.de"}, {name = "Moritz Hellmich"}]
dynamic = ["version", "description"]